# This is a sample docker-compose.yml for our meteorjs webapp

# version: '3' # obsolete
services:
  docker-meteorjs-webapp:
    container_name: docker-meteorjs-webapp
    image: docker-meteorjs-webapp:latest
    # network_mode: host # use the host's network (e.g., Docker Desktop)
    ports:
      - 3000:3000
    volumes:
      - ../:/app 

