# This is a sample docker-compose.yml for our meteorjs webapp

# version: '3' # STUB: obsolete, but required if still using ubuntu 22.04 host (not for 24.04)
services:
  docker-meteorjs-webapp:
    container_name: docker-meteorjs-webapp
    image: docker-meteorjs-webapp:latest
    # STUB: use the host's network (e.g., Docker Desktop)
    # network_mode: "host" 
    ports:
      - 3000:3000
    volumes:
      - ../:/app 
      

